target-version = "py312"
line-length = 119

[lint]
select = ["ALL"]
ignore = [
    "D",
    "FIX002",   # use TODO
    "TD002",    #
    "TD003",    #
    "PLR0913",  # Because of my lazy
    "ERA001",   # Ocurring False Positive
    "FBT001",   # flag parameter
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401"      # The imported class is rarely used within __init__.py
]
"tests/**.py" = [
    "S101",     # pytest use assert
    "SLF001",   # test private method
]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel"
]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false